import * as expanderDescription from './expandDescription.js';
import * as expanderBrands from './expandBrands.js';
import * as expanderSerivce from './expandService.js';
import * as asideMenu from './mobile-aside-menu.js';
import * as modalFeedback from './modalFeedback.js';
import * as modalGetCall from './modalGetCall.js';
import * as swiperBrands from './swiperBrands.js';
import * as swiperPrices from './swiperPrices.js';
import * as swiperService from './swiperService.js';
import '../scss/style.scss';